# Generated by Django 2.2.1 on 2019-05-23 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postgres_audit_triggers', '0003_metadata_tweak'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['table_name'], name='postgres_a_table_n_745812_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['action_tstamp_tx'], name='postgres_a_action__d42ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['action'], name='postgres_a_action_116cf9_idx'),
        ),
    ]
